image: htravado/testing:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

test:
  stage: test
  script:
    - cd build
    - ctest --output-on-failure